spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartshape_db
    username: smartshape
    password: smartshape123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true